apiVersion: v1
kind: Secret
metadata:
  name: tacklebox-secrets
type: Opaque
stringData:
  GEMINI_API_KEY: AIzaSyCLahvvfbII5ACk2ZoC7JeDyL3RQ-AfDsU
  MONGO_ROOT_USER: bsratzlaff@gmail.com
  MONGO_ROOT_PASSWORD: d8V^4zkUD7z%UG