apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # 🛠️ CRITICAL FIX: The absolute, bulletproof Docker Windows mount path
    path: "/c/Users/bsrat/Code/backend_logs"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi