apiVersion: apps/v1
kind: Deployment
metadata:
  name: tacklebox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tacklebox
  template:
    metadata:
      labels:
        app: tacklebox
    spec:
      containers:
      - name: my-tacklebox
        image: my-tacklebox:v5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tacklebox-secrets
                  key: GEMINI_API_KEY
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: tacklebox-secrets
                  key: MONGO_ROOT_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: tacklebox-secrets
                  key: MONGO_ROOT_PASSWORD
            - name: MONGO_HOST
              value: "mongodb-service"
---
apiVersion: v1
kind: Service
metadata:
  name: tacklebox-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 3000
  selector:
    app: tacklebox